#+TITLE: Jesse Wattenbarger Customizations
#+OPTIONS: toc:2 num:nil ^:nil

* Trying this out
Here I'm just trying to get started with this new config using
emacs24-starter kit literate programming style.  I'm a little confused
already because my normal keybindings aren't working. Ah, apparently
org is freaking out. Let's see what version of org my emacs is using.

Yep, it's not being loaded right.  I think I want to try out cask, but
I'm not sure if it will conflict with starter kit.  For now, I'm just
going to install org under src and restart emacs.  Just to make sure
it gets loaded, for now, I'll define ORG_HOME inside init.el

#+BEGIN_SRC emacs-lisp
(defvar my-home (getenv "HOME"))
(defvar my-src (expand-file-name "src" my-home))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(setenv "ORG_HOME" (expand-file-name ".emacs.d/src/org-mode" my-home))
#+END_SRC

* Does org-mode work better now?
It looks like org-mode might be working better now. Yes, the enter key
does what I expect, and auto-fill is working.

* Packages
I'm not sure if the starter-kit is supposed to install packages
automatically, but it keeps erroring here and there after I add more
of the starter kit below. It's annoying to constantly have to
package-install after you see it fail, so let's just use cask.
  - [[http://cask.github.io/][Cask Website]]

#+BEGIN_SRC sh
mkdir -p $HOME/git
git clone https://github.com/cask/cask.git $HOME/src/cask
#+END_SRC

#+BEGIN_SRC sh
export PATH="$HOME/src/cask/bin:$PATH"
#+END_SRC

#+BEGIN_SRC sh
cd $HOME/.emacs.d/
cask init
#+END_SRC

#+BEGIN_SRC emacs-lisp
(require 'cask (expand-file-name "cask/cask.el" my-src))
(cask-initialize)
#+END_SRC

** Using Cask
Run cask install to install dependencies.
#+BEGIN_SRC sh
cask install
#+END_SRC

* Load more of starter-kit
** Python
#+BEGIN_SRC emacs-lisp
(starter-kit-load "python")
#+END_SRC

** Eshell
 #+BEGIN_SRC emacs-lisp
 (starter-kit-load "eshell")
 #+END_SRC

** Lisp
This should load elisp, scheme, cl, and clojure stuff.
According to 
#+BEGIN_SRC emacs-lisp
(starter-kit-load "lisp")
#+END_SRC
